name: factorio-headless
version: '0.16.51'
summary: Headless server for Factorio running as a system service
description: |
  Change configuration options

    sudo snap get factorio-headless
    sudo snap set factorio-headless admins='["kovarex"]'
    sudo snap set factorio-headless game-password=1337
    sudo snap restart factorio-headless

  Control the service and check status

    sudo snap start factorio-headless
    sudo snap stop factorio-headless
    sudo snap start --enable factorio-headless
    sudo snap stop --disable factorio-headless
    sudo snap services | grep factorio-headless

  Server files location

    ls /var/snap/factorio-headless/common

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  server:
    command: factorio/factorio-headless.server
    daemon: forking
    stop-timeout: 20s
    stop-command: factorio/factorio-headless.server-stop
    restart-condition: never
    plugs: [network, network-bind]

  factorio-headless:
    command: factorio/bin/x64/factorio
    completer: factorio/bash-completion
    plugs: [network, network-bind, home]

parts:
  factorio:
    plugin: dump
    source: https://www.factorio.com/get-download/$SNAPCRAFT_PROJECT_VERSION/headless/linux64
    source-type: tar
    stage:
      - -factorio/config-path.cfg
    organize:
      '*' : factorio/

  config:
    after:
      - factorio
    source: config/
    plugin: dump
    organize:
      '*' : factorio/

  common:
    source: common/
    plugin: dump
    organize:
      '*' : common/
